// Code generated by MockGen. DO NOT EDIT.
// Source: service/voucher_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "bookcabin_project/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVoucherService is a mock of VoucherService interface.
type MockVoucherService struct {
	ctrl     *gomock.Controller
	recorder *MockVoucherServiceMockRecorder
}

// MockVoucherServiceMockRecorder is the mock recorder for MockVoucherService.
type MockVoucherServiceMockRecorder struct {
	mock *MockVoucherService
}

// NewMockVoucherService creates a new mock instance.
func NewMockVoucherService(ctrl *gomock.Controller) *MockVoucherService {
	mock := &MockVoucherService{ctrl: ctrl}
	mock.recorder = &MockVoucherServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoucherService) EXPECT() *MockVoucherServiceMockRecorder {
	return m.recorder
}

// CheckExist mocks base method.
func (m *MockVoucherService) CheckExist(flight_number, date string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExist", flight_number, date)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExist indicates an expected call of CheckExist.
func (mr *MockVoucherServiceMockRecorder) CheckExist(flight_number, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExist", reflect.TypeOf((*MockVoucherService)(nil).CheckExist), flight_number, date)
}

// Generate mocks base method.
func (m *MockVoucherService) Generate(voucher model.Voucher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", voucher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockVoucherServiceMockRecorder) Generate(voucher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockVoucherService)(nil).Generate), voucher)
}
